# Generated by Django 4.1 on 2022-08-22 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='stock_deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_code', models.CharField(max_length=15)),
                ('share', models.IntegerField()),
                ('bought_date', models.DateField()),
                ('bought_price', models.FloatField()),
                ('current_price', models.FloatField()),
                ('profit_and_loss', models.FloatField()),
            ],
        ),
    ]
