# Generated by Django 4.1 on 2022-08-23 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_stock_deal_company_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock_deal',
            name='current_price',
        ),
        migrations.RemoveField(
            model_name='stock_deal',
            name='profit_and_loss',
        ),
    ]
