# Generated by Django 4.1 on 2022-08-23 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_stock_deal_current_price_stock_deal_profit_and_loss'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock_deal',
            name='duration',
            field=models.IntegerField(default=0),
        ),
    ]
