# Generated by Django 4.1 on 2022-08-23 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_stock_deal_bought_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock_deal',
            name='bought_date',
            field=models.DateField(),
        ),
    ]
